sonar.organization=j-k-laurens
sonar.projectKey=J-K-Laurens_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.sources=back/src/main/java,front/src

# Configuration Java - binaires compilés
sonar.java.binaries=back/target/classes

# Configuration TypeScript/JavaScript
sonar.typescript.lcov.reportPaths=front/coverage/lcov.info
sonar.javascript.lcov.reportPaths=front/coverage/lcov.info

# Exclusions générales
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/.scannerwork/**,**/*.log

# Tests
sonar.tests=back/src/test/java,front/src
sonar.test.inclusions=**/*Test.java,**/*.spec.ts    