sonar.projectKey=Projet-10-frontend
sonar.projectName=Projet 10 Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.token=<replace with your SonarQube token>