sonar.organization=j-k-laurens
sonar.projectKey=J-K-Laurens_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
sonar.projectName=bobapp
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info