name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and analyze with SonarQube
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze with SonarQube
        working-directory: back
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Projet-10 -Dsonar.projectName='Projet 10' -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqa_daec473a6c124eb7bb0fa956db434d99242ed23a

