# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    defaults:
      run:
        working-directory: front

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
    - name: Upload Coverage Reports
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage-report
        path: front/coverage/
    - name: Analyze with SonarQube
      working-directory: front
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        npx sonar-scanner -Dsonar.projectKey=Projet-10-frontend -Dsonar.projectName="Projet 10 Frontend" -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN -Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/*.spec.ts" -Dsonar.exclusions="**/node_modules/**" -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
